=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/PaymentForm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="message">
		<xs:complexType>
			<xs:attribute name="text" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Текстовое сообщение об ошибке</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parameter">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="template" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation>
						Флаг, определяющий используется ли действие в шаблоне
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="order" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>
						Число, определяющее порядок исполнения
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="payment-form">
		<xs:annotation>
			<xs:documentation>Метаданные описывающие форму платежа</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="implementation">
					<xs:annotation>
						<xs:documentation>Класс имплементации платежа</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="template-implementation" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Класс имплементации шаблона платежа</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="statemachine" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Положение statemachine</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>

				<xs:element name="extended-metadata-loader" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Класс загрузчик доп полей</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="withdraw-options" minOccurs="0" type="OperationOptions">
					<xs:annotation>
						<xs:documentation>Настройки отзыва документа</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="edit-options" minOccurs="0" type="OperationOptions">
					<xs:annotation>
						<xs:documentation>Настройки редактирования документа</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="list-form" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="need-parent" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="value" type="xs:boolean" default="false"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="field" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="dictionaries" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Статические справочники формы</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entity-list" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:any namespace="##any" processContents="skip" minOccurs="0"
										        maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Элемент справочника вида  ключ-значение</xs:documentation>
											</xs:annotation>
										</xs:any>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Название справочника</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="form-validators" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Валидаторы формы</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="form-validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя формы</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" use="required">
				<xs:annotation>
					<xs:documentation>Название отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="templateName" use="optional">
				<xs:annotation>
					<xs:documentation>Название шаблона</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="detailedDescription" use="optional">
				<xs:annotation>
					<xs:documentation>Описание отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="confirmDescription" use="optional">
				<xs:annotation>
					<xs:documentation>Подтверждение отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="form-validator">
		<xs:annotation>
			<xs:documentation>Валидатор осуществляющий проверку полей формы (например, что первая дата в периоде дат не превышает вторую)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="field-ref" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="error-field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Класс реализующий данный валидатор</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="mode" type="xs:string" default="document|template">
				<xs:annotation>
					<xs:documentation>
                        режим работы валидатора. данное поле используется стратегиями валдиции.
                        см com.rssl.common.forms.processing.ValidationStrategy
                    </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="validator">
		<xs:annotation>
			<xs:documentation>Проверка отдельного поля формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя класса валидатора</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="mode" type="xs:string" default="document|template|mobile">
				<xs:annotation>
					<xs:documentation>
                        режим работы валидатора. данное поле используется стратегиями валдиции.
                        см com.rssl.common.forms.processing.ValidationStrategy
                    </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field">
		<xs:annotation>
			<xs:documentation>Поле формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="validators" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Набор валидаторов для данного поля</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formater" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Класс форматирующий вывод</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="parser" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Класс для разбора ввода</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя поля формы, используется в Payment -&gt; HTML преобразовании</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="source" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>XPath выражение для получения значения поля из Payment</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Описание поля, используется для вывода сообщеий валидации</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" type="xs:string" use="optional" default="string">
				<xs:annotation>
					<xs:documentation>Тип поля, по умочанию string</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="subType" use="optional" default="dinamic">
				<xs:annotation>
					<xs:documentation>Доп. тип поля, по умолчанию dinamic</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="dinamic"/>
                        <xs:enumeration value="static"/>
                    </xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute name="category" use="optional">
				<xs:annotation>
					<xs:documentation>Бизнес категория поля</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="phone"/>
                        <xs:enumeration value="surname"/>
                        <xs:enumeration value="extended_phone"/>
                        <xs:enumeration value="street"/>
                        <xs:enumeration value="date"/>
                        <xs:enumeration value="full_masked"/>
                        <xs:enumeration value="external_card"/>
                    </xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute name="mask" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Маска поля</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="signable" default="false" type="xs:boolean"/>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>выражение булевого типа. Если результат true, то поле включено.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="fromApi" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Начиная с какой версии mobile API включается данное поле(только для mobile Api)(либо fromApi либо toApi)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="toApi" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>До какой версии mobile API включается данное поле(только для mobile Api)(либо fromApi либо toApi)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Вычислимое значение поля.</xs:documentation>
			</xs:annotation>
			</xs:attribute>
			<xs:attribute name="inital" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Начальное значение поля.</xs:documentation>
			</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field-ref">
		<xs:annotation>
			<xs:documentation>Ссылки на поля требуемые для проверки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Ссылка на field-&gt;name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>Свойство</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Устанавливает добавочный атрибут</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:annotation>
			<xs:documentation>Параметры валидации</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя параметра валидатора</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="error-field">
   		<xs:annotation>
   			<xs:documentation>Поле, которое нужно подсвечивать как ошибочное</xs:documentation>
   		</xs:annotation>
   		<xs:complexType mixed="true">
   			<xs:attribute name="name" type="xs:string" use="required">
   				<xs:annotation>
   					<xs:documentation>Ссылка на field-&gt;name</xs:documentation>
   				</xs:annotation>
   			</xs:attribute>
   		</xs:complexType>
   	</xs:element>

	<xs:complexType name="Actions">
	    <xs:sequence>
	        <xs:element ref="action" minOccurs="1" maxOccurs="unbounded"/>
	    </xs:sequence>
	</xs:complexType>

	<xs:complexType name="OperationOptions">
		<xs:sequence>
			<xs:element ref="form"/>
			<xs:element ref="check" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="check">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="form">
		<xs:annotation>
			<xs:documentation>Форма</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/taatta/TaxPayment/TaxPayment.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="TaxPayment" description="Оплата налогов"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
	<implementation class="com.rssl.phizic.business.documents.payments.RurPayment"/>
    <withdraw-options>
	   <form name="RecallPayment"/>
	   <check class="com.rssl.phizic.business.documents.metadata.checkers.DocumentStateChecker">
		   <parameter name="state">intermediate</parameter>
	   </check>
	</withdraw-options>
	<fields>
		<field
				name="documentNumber"
				description="Номер документа"
				type="string"
				source="document-number">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			</validators>
		</field>
		<field name="state"
		       source="state"
		       description="Статус платежа"
		       type="string"/>
		<field
				name="documentDate"
				description="Дата документа"
				type="date"
				source="document-date"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
			</validators>
		</field>

		<field name="admissionDate"
		       source="admissionDate"
		       type="date"
		       description="Дата приема плaтежа банком">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.DateFieldValidator"/>
			</validators>
		</field>

		<field
				name="payerName"
				description="ФИО плательщика"
				type="string"
				source="payer-name"
				signable="true">
		</field>
		<field
				name="currency"
				description="Валюта перевода"
				source="extra-parameters/parameter[@name='currency']/@value"
				type="string"
				signable="true">
		</field>
		<field
				name="payerAccountSelect"
				description="Счет списания"
				type="account"
				source="payer-account"
				signable="true">

			<validators>
				<validator class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.phizic.business.payments.forms.validators.UserAccountValidator"/>
			</validators>
		</field>

		<field
				name="amount"
				description="Сумма"
				source="amount"
				type="money"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.MoneyFieldValidator">
					<message text="Значение суммы к оплате должно быть в диапазоне 0,01 - 999999999,99"/>
				</validator>
				<validator class="com.rssl.common.forms.validators.NumericRangeValidator">
					<message text="Значение суммы перевода должно быть в диапазоне 0,01 - 999999999,99"/>
					<parameter name="minValue">0.01</parameter>
					<parameter name="maxValue">999999999.99</parameter>
				</validator>
			</validators>
		</field>
		<field
				name="receiverName"
				description="Наименование получателя платежа"
				source="receiver-name"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			</validators>
		</field>

		<field
				name="receiverINN"
				description="ИНН получателя платежа"
				source="receiver-inn"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.RegexpFieldValidator">
					<message text="ИНН получателя платежа должен состоять из 10 цифр"/>
					<parameter name="regexp">^\d{10}$</parameter>
				</validator>
			</validators>
		</field>

		<field
				name="receiverKPP"
				description="КПП получателя платежа"
				source="receiver-kpp"
				type="string"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.RegexpFieldValidator">
					<message text="КПП получателя платежа должен состоять из 9 цифр"/>
					<parameter name="regexp">^\d{9}$</parameter>
				</validator>
			</validators>
		</field>

		<field
				name="receiverAccount"
				description="Счет получателя"
				type="string"
				source="receiver-account"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.RegexpFieldValidator">
					<message text="Счет получателя должен состоять из 20 цифр"/>
					<parameter name="regexp">^\d{20}$</parameter>
				</validator>
			</validators>
		</field>

		<field
				name="receiverBank"
				description="Наименование банка получателя"
				source="extra-parameters/parameter[@name='receiver-bank']/@value"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			</validators>
		</field>

		<field
				name="receiverBIC"
				description="БИК банка получателя"
				type="string"
				source="receiver-bic"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.RegexpFieldValidator">
					<message text="БИК должен состоять из 9 цифр"/>
					<parameter name="regexp">^\d{9}$</parameter>
				</validator>
			</validators>
		</field>

		<field
				name="receiverCorAccount"
				description="Кор.счет банка получателя"
				type="string"
				source="receiver-cor-account"
				signable="true">
			<validators>
				<validator class="com.rssl.common.forms.validators.RegexpFieldValidator">
					<message text="Кор.Счет должен состоять из 20 цифр"/>
					<parameter name="regexp">^\d{20}$</parameter>
				</validator>
			</validators>
		</field>

		<field
				name="ground"
				description="Назначение платежа"
				source="ground"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.RegexpFieldValidator">
					<message text="Назначение платежа не должно превышать 200 символов"/>
					<parameter name="regexp">^.{1,200}$</parameter>
				</validator>
			</validators>
		</field>

		<field
				name="taxStatus"
				description="Статус"
				source="extra-parameters/parameter[@name='tax-status']/@value"
				type="string"
				signable="true">
			
		</field>

		<field
				name="taxKBK"
				description="Код КБК"
				source="extra-parameters/parameter[@name='tax-kbk']/@value"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			</validators>
		</field>

		<field
				name="taxOKATO"
				description="ОКАТО"
				source="extra-parameters/parameter[@name='tax-okato']/@value"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			</validators>
		</field>

		<field
				name="taxGround"
				description="Показатель основания платежа"
				source="extra-parameters/parameter[@name='tax-ground']/@value"
				type="string"
				signable="true">
			
		</field>

		<field
				name="taxType"
				description="Показатель типа платежа"
				source="extra-parameters/parameter[@name='tax-type']/@value"
				type="string"
				signable="true">
			
		</field>

		<field
				name="taxDocumentDate"
				description="Дата налогового документа"
				source="extra-parameters/parameter[@name='tax-document-date']/@value"
				type="string"
				signable="true">
			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.TaxDateFieldValidator"/>
			</validators>
		</field>

		<field
				name="taxDocumentNumber"
				description="Номер налогового документа"
				source="extra-parameters/parameter[@name='tax-document-number']/@value"
				type="string"
				signable="true">

		</field>

		<field
				name="taxPeriod1"
				description="Период: Число"
				source="extra-parameters/parameter[@name='tax-period1']/@value"
				type="string"
				signable="true">

		</field>

		<field
				name="taxPeriod2"
				description="Период: Месяц"
				source="extra-parameters/parameter[@name='tax-period2']/@value"
				type="string"
				signable="true">

		</field>

		<field
				name="taxPeriod3"
				description="Период: Год"
				source="extra-parameters/parameter[@name='tax-period3']/@value"
				type="string"
				signable="true">
			
		</field>

		<field
				name="commissionAmount"
				description="Сумма коммисии"
				source="commission"
				type="money"
				signable="true">
		</field>

	</fields>

	<form-validators>
		<form-validator mode="document" class="com.rssl.common.forms.validators.TaxPeriodValidator">
			<message text="Проверьте правильность заполнения периода"/>
			<field-ref name="day">taxPeriod1</field-ref>
			<field-ref name="month">taxPeriod2</field-ref>
			<field-ref name="year">taxPeriod3</field-ref>
			<field-ref name="ground">taxGround</field-ref>
		</form-validator>
		<form-validator mode="document" class="com.rssl.phizic.business.payments.forms.validators.AccountAmountValidator">
			<field-ref name="account">payerAccountSelect</field-ref>
			<field-ref name="amount">amount</field-ref>
		</form-validator>
	</form-validators>
</payment-form>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/sbrf/DelayInvoiceSubscriptionClaim/DelayInvoiceSubscriptionClaim.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="DelayInvoiceSubscriptionClaim" description="Приостановка подписки"
              confirmDescription="Подписка успешно приостановлена."
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
	<implementation class="com.rssl.phizic.business.documents.payments.DelayInvoiceSubscriptionClaim"/>
	<statemachine name="DelayInvoiceSubscriptionClaim"/>
    <extended-metadata-loader class="com.rssl.phizic.business.payments.forms.meta.basket.CreateInvoiceSubscriptionClaimMetadataLoader"/>
    <fields>
        <field name="nameService"
               description="Наименование услуги в биллинговой системе"
               type="string"
               source="extra-parameters/parameter[@name='nameService']/@value"/>

        <field name="billingCode"
               description="Идентфикатор билинговой системы"
               type="string"
               source="extra-parameters/parameter[@name='provider-billing-code']/@value"/>

        <field name="receiverName"
               description="Наименование получателя"
               type="string"
               source="receiver-name"
               signable="true"/>

        <field name="subscriptionName"
               source="extra-parameters/parameter[@name='subscription-name']/@value"
               type="string"
               description="Наименование подписки"/>

        <field name="subscriptionId"
               source="extra-parameters/parameter[@name='invoice-sub-id']/@value"
               type="string"
               description="Идентификатор подписки"/>

        <field name="state"
               source="state"
               description="Статус платежа"
               type="string"/>

        <field name="autoSubNumber"
               source="extra-parameters/parameter[@name='long-offer-number']/@value"
               description="Номер платежа"
               type="string"/>

        <field name="fromAccountSelect"
               description="Счет/карта списания"
               type="string"
               source="payer-account"/>

        <field name="fromAccountName"
               source="extra-parameters/parameter[@name='from-account-name']/@value"
               description="Наименование источника списания"
               type="string"/>

        <field name="fromResourceCurrency"
               description="Валюта"
               source="extra-parameters/parameter[@name='from-resource-currency']/@value"
               type="string"/>

        <field name="fromResourceRest"
               source="extra-parameters/parameter[@name='from-resource-rest']/@value"
               description="Остаток на счете списания"
               type="string"/>

        <field name="groupName"
               description="Наименование группы услуг"
               source="extra-parameters/parameter[@name='group-name']/@value"
               type="string"/>

        <field name="invoiceAccountName"
               description="Название выставляемого счета"
               source="extra-parameters/parameter[@name='invoice-account-name']/@value"
               type="string"/>

        <field name="invoiceInfo"
               description="Информация о выставлениии счета по данной услуге"
               source="extra-parameters/parameter[@name='invoice-info']/@value"
               type="string"/>
    </fields>
</payment-form>
