=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/PaymentList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="payment-list">
		<xs:annotation>
			<xs:documentation>Корневой элемент</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="filter">
					<xs:annotation>
						<xs:documentation>Фильтр списка</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fields">
								<xs:annotation>
									<xs:documentation>Поля фильтра списка</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="field" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="form-validators" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Валидаторы формы</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="form-validator" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:choice>
					<xs:element ref="hql-query"/>
					<xs:element name="sql-query">
						<xs:annotation>
							<xs:documentation>sql-запрос к БД</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="title" use="required">
				<xs:annotation>
					<xs:documentation>Титул списка</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description">
				<xs:annotation>
					<xs:documentation>Описание </xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="message">
		<xs:complexType>
			<xs:attribute name="text" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="form-validator">
		<xs:annotation>
			<xs:documentation>Проверка полей формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="field-ref" maxOccurs="unbounded"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Класс реализующий данный валидатор</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="template" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation>Используется ли данный валидатор при проверке шаблонов</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="validator">
		<xs:annotation>
			<xs:documentation>Проверка отдельного поля формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="template" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation>Используется ли данный валидатор при проверке шаблонов</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="field">
		<xs:annotation>
			<xs:documentation>Поле фильтра</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="validators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formater" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="parser" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя поля формы, используется в Payment -> HTML преобразовании</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Описание поля, используется для вывода сообщеий валидации</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" type="xs:string" use="optional" default="string">
				<xs:annotation>
					<xs:documentation>Тип поля, по умочанию string</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="field-ref">
		<xs:annotation>
			<xs:documentation>Ссылки на поля требуемые для проверки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Ссылка на field->name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:annotation>
			<xs:documentation>Параметры валидации</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя параметра</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sql-query"/>
	<xs:element name="hql-query">
		<xs:annotation>
			<xs:documentation>hql-запрос к БД</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="returnKey">
					<xs:complexType>
						<xs:attribute name="property" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Свойство бина из которого будет извлекаться значение</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="name" type="xs:string">
							<xs:annotation>
								<xs:documentation>Имя результирующего тега. По умолчанию используется property</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="index" type="xs:unsignedLong">
							<xs:annotation>
								<xs:documentation>Индекс бина в массиве. (В случае если запрос возвращает несколько бинов)</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:sequence>
					<xs:element name="return" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="property" type="xs:string" use="required">
								<xs:annotation>
									<xs:documentation>Свойство бина из которого будет извлекаться значение</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="name" type="xs:string">
								<xs:annotation>
									<xs:documentation>Имя результирующего тега. По умолчанию используется property</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="index" type="xs:unsignedLong">
								<xs:annotation>
									<xs:documentation>Индекс бина в массиве. (В случае если запрос возвращает несколько бинов)</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/demo/GoodsAndServicesPayment/GoodsAndServicesPayment.list-pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../PaymentList.xsd" 
		title='Список переводов "Оплата покупок и услуг"'
>
	<filter>
		<fields>
			<field name="state" description="Статус"/>
			<field name="state_list" description="Вспомогательный статус"/>
			<field name="minAmount" description="Минимальная сумма" type="money">
				<validators>
					<validator class="com.rssl.common.forms.validators.MoneyFieldValidator"/>
				</validators>
			</field>
			<field name="maxAmount" description="Максимальная сумма" type="money">
				<validators>
					<validator class="com.rssl.common.forms.validators.MoneyFieldValidator"/>
				</validators>
			</field>
			<field name="fromDate" description="Начальная дата" type="date">
				<validators>
					<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				</validators>	
			</field>
			<field name="toDate" description="Конечная дата" type="date">
				<validators>
					<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				</validators>	
			</field>
			<field name="payerAccount" description="Счет списания"/>
			<field name="appointment" description="Назначение платежа"/>
		</fields>
		<form-validators>
			<form-validator class="com.rssl.common.forms.validators.CompareValidator">
				<message text="Конечная дата должна быть больше либо равна начальной"/>
				<field-ref name="obj1">fromDate</field-ref>
				<field-ref name="obj2">toDate</field-ref>
				<parameter name="operator">le</parameter>
			</form-validator>
		</form-validators>
	</filter>
	<hql-query>
		<returnKey property="id"/>
		<return property="chargeOffAccount"/>
		<return property="documentNumber"/>
		<return property="receiverName"/>
		<return property="chargeOffAmount.decimal"/>
		<return property="chargeOffAmount.currency.code"/>
		<return property="state.code"/>
		<return property="dateCreated"/>
		<![CDATA[
			select payment
				from com.rssl.phizic.business.documents.payments.GoodsAndServicesPayment as payment
			where   payment.owner.id = :loginId
				and (:state_list is null      or :state_list = '' or payment.state.code in (:state))
				and (:minAmount is null       or payment.chargeOffAmount.decimal >= :minAmount)
				and (:maxAmount is null       or payment.chargeOffAmount.decimal <= :maxAmount)
				and (:fromDate is null        or payment.dateCreated >= :fromDate)
				and (:toDate is null          or payment.dateCreated <= :toDate  )
				and (:payerAccount is null    or :payerAccount = '' or payment.chargeOffAccount = :payerAccount)
				and (:appointment is null     or :appointment ='' or payment.attributes['appointment'].stringValue = :appointment)
		    order by payment.dateCreated asc, payment.id desc
		]]>
	</hql-query>
</payment-list>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/sevb/AccountOpeningClaim/AccountOpeningClaim.list-pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../settings/forms/PaymentList.xsd"
		title="Список заявок на открытие счета"
		>
	<filter>
		<fields>
			<field name="state" description="Статус"/>
			<field name="state_list" escription="Вспомогательный статус"/>
			<field name="refusingReason" description="Причина отказа"/>

			<field name="fromDate" description="Начальная дата" type="date">
				<validators>
					<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				</validators>
			</field>

			<field name="toDate" description="Конечная дата" type="date">
				<validators>
					<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				</validators>
			</field>

			<field name="claimType" description="Тип заявки"/>
		</fields>

		<form-validators>
			<form-validator class="com.rssl.common.forms.validators.CompareValidator">
				<message text="Конечная дата должна быть больше либо равна начальной"/>
				<field-ref name="obj1">fromDate</field-ref>
				<field-ref name="obj2">toDate</field-ref>
				<parameter name="operator">le</parameter>
			</form-validator>
		</form-validators>
	</filter>

	<hql-query>
		<returnKey property="id"/>
		<return property="dateCreated"/>
		<return property="changed"/>
		<return property="state.code"/>
		<return property="state.category"/>
		<return property="formName"/>
		<return property="fromAccount"/>
        <return property="state.description"/>
		<!--<return property="department"/>-->
<!--
		<return property="refusingReason"/>

-->
		<![CDATA[
		select claim
					from com.rssl.phizic.business.documents.DepositOpeningClaim claim
					where claim.owner.id = :loginId
						and (:state_list is null   or :state_list = '' or claim.state.code in (:state))
						and (:fromDate is null  or claim.dateCreated >= :fromDate)
						and (:toDate is null    or claim.dateCreated < :toDate + 1 )
						and (:claimType is null or :claimType = '' or claim.formName = :claimType)
		            order by claim.dateCreated desc, claim.changed desc, claim.id desc
			    ]]>
	</hql-query>
</payment-list>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/demo/CardReplenishmentPayment/CardReplenishmentPayment.list-pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../PaymentList.xsd"
		title="Список платежей на пополнение карты"
		>
	<filter>
		<fields>
			<field name="state" description="Статус"/>
			<field name="state_list" description="Вспомогательный статус"/>
			<field name="minAmount" description="Минимальная сумма" type="money">
				<validators>
					<validator class="com.rssl.common.forms.validators.MoneyFieldValidator"/>
				</validators>
			</field>
			<field name="maxAmount" description="Максимальная сумма" type="money">
				<validators>
					<validator class="com.rssl.common.forms.validators.MoneyFieldValidator"/>
				</validators>
			</field>
			<field name="fromDate" description="Начальная дата" type="date">
				<validators>
					<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				</validators>
			</field>
			<field name="toDate" description="Конечная дата" type="date">
				<validators>
					<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				</validators>
			</field>
			<field name="currencyCode" description="Валюта"/>
			<field name="cardNumber" description="Номер карты"/>
		</fields>
		<form-validators>
			<form-validator class="com.rssl.common.forms.validators.CompareValidator">
				<message text="Конечная дата должна быть больше либо равна начальной"/>
				<field-ref name="obj1">fromDate</field-ref>
				<field-ref name="obj2">toDate</field-ref>
				<parameter name="operator">le</parameter>
			</form-validator>
		</form-validators>
	</filter>
	<hql-query>
		<returnKey property="id"/>
		<return property="dateCreated"/>
		<return property="attributes.cardNumber.value"/>
		<return property="chargeOffAmount.decimal"/>
		<return property="chargeOffAmount.currency.code"/>
		<return property="state.code"/>
		<return property="documentNumber"/>
		<![CDATA[
			select payment
			from com.rssl.phizic.business.documents.InternalTransfer as payment
			where payment.formName = 'CardReplenishmentPayment'
			    and payment.owner.id = :loginId
			    and (:state_list is null      or :state_list = '' or payment.state.code in (:state))
				and (:minAmount is null       or payment.chargeOffAmount.decimal >= :minAmount)
				and (:maxAmount is null       or payment.chargeOffAmount.decimal <= :maxAmount)
				and (:fromDate is null     or payment.dateCreated >= :fromDate)
				and (:toDate is null       or payment.dateCreated <= :toDate  )
				and (:cardNumber is null   or :cardNumber = ''   or payment.attributes['cardNumber'].stringValue in
						(SELECT cardlink.number from com.rssl.phizic.business.resources.external.CardLink cardlink where cardlink.login.id=:loginId and cardlink.externalId=:cardNumber)
					)
				and (:currencyCode is null or :currencyCode = '' or payment.chargeOffAmount.currency = :currencyCode)
            order by payment.dateCreated asc, payment.id desc
	    ]]>
	</hql-query>
</payment-list>
