=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/PaymentForm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="message">
		<xs:complexType>
			<xs:attribute name="text" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Текстовое сообщение об ошибке</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parameter">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="template" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation>
						Флаг, определяющий используется ли действие в шаблоне
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="order" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>
						Число, определяющее порядок исполнения
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="payment-form">
		<xs:annotation>
			<xs:documentation>Метаданные описывающие форму платежа</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="implementation">
					<xs:annotation>
						<xs:documentation>Класс имплементации платежа</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="template-implementation" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Класс имплементации шаблона платежа</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="statemachine" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Положение statemachine</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>

				<xs:element name="extended-metadata-loader" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Класс загрузчик доп полей</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="withdraw-options" minOccurs="0" type="OperationOptions">
					<xs:annotation>
						<xs:documentation>Настройки отзыва документа</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="edit-options" minOccurs="0" type="OperationOptions">
					<xs:annotation>
						<xs:documentation>Настройки редактирования документа</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="list-form" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="need-parent" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="value" type="xs:boolean" default="false"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="field" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="dictionaries" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Статические справочники формы</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entity-list" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:any namespace="##any" processContents="skip" minOccurs="0"
										        maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Элемент справочника вида  ключ-значение</xs:documentation>
											</xs:annotation>
										</xs:any>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Название справочника</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="form-validators" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Валидаторы формы</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="form-validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя формы</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" use="required">
				<xs:annotation>
					<xs:documentation>Название отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="templateName" use="optional">
				<xs:annotation>
					<xs:documentation>Название шаблона</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="detailedDescription" use="optional">
				<xs:annotation>
					<xs:documentation>Описание отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="confirmDescription" use="optional">
				<xs:annotation>
					<xs:documentation>Подтверждение отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="form-validator">
		<xs:annotation>
			<xs:documentation>Валидатор осуществляющий проверку полей формы (например, что первая дата в периоде дат не превышает вторую)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="field-ref" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="error-field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Класс реализующий данный валидатор</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="mode" type="xs:string" default="document|template">
				<xs:annotation>
					<xs:documentation>
                        режим работы валидатора. данное поле используется стратегиями валдиции.
                        см com.rssl.common.forms.processing.ValidationStrategy
                    </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="validator">
		<xs:annotation>
			<xs:documentation>Проверка отдельного поля формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя класса валидатора</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="mode" type="xs:string" default="document|template|mobile">
				<xs:annotation>
					<xs:documentation>
                        режим работы валидатора. данное поле используется стратегиями валдиции.
                        см com.rssl.common.forms.processing.ValidationStrategy
                    </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field">
		<xs:annotation>
			<xs:documentation>Поле формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="validators" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Набор валидаторов для данного поля</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formater" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Класс форматирующий вывод</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="parser" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Класс для разбора ввода</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя поля формы, используется в Payment -&gt; HTML преобразовании</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="source" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>XPath выражение для получения значения поля из Payment</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Описание поля, используется для вывода сообщеий валидации</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" type="xs:string" use="optional" default="string">
				<xs:annotation>
					<xs:documentation>Тип поля, по умочанию string</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="subType" use="optional" default="dinamic">
				<xs:annotation>
					<xs:documentation>Доп. тип поля, по умолчанию dinamic</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="dinamic"/>
                        <xs:enumeration value="static"/>
                    </xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute name="category" use="optional">
				<xs:annotation>
					<xs:documentation>Бизнес категория поля</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="phone"/>
                        <xs:enumeration value="surname"/>
                        <xs:enumeration value="extended_phone"/>
                        <xs:enumeration value="street"/>
                        <xs:enumeration value="date"/>
                        <xs:enumeration value="full_masked"/>
                        <xs:enumeration value="external_card"/>
                    </xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute name="mask" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Маска поля</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="signable" default="false" type="xs:boolean"/>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>выражение булевого типа. Если результат true, то поле включено.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="fromApi" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Начиная с какой версии mobile API включается данное поле(только для mobile Api)(либо fromApi либо toApi)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="toApi" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>До какой версии mobile API включается данное поле(только для mobile Api)(либо fromApi либо toApi)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Вычислимое значение поля.</xs:documentation>
			</xs:annotation>
			</xs:attribute>
			<xs:attribute name="inital" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Начальное значение поля.</xs:documentation>
			</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field-ref">
		<xs:annotation>
			<xs:documentation>Ссылки на поля требуемые для проверки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Ссылка на field-&gt;name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>Свойство</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Устанавливает добавочный атрибут</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:annotation>
			<xs:documentation>Параметры валидации</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя параметра валидатора</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="error-field">
   		<xs:annotation>
   			<xs:documentation>Поле, которое нужно подсвечивать как ошибочное</xs:documentation>
   		</xs:annotation>
   		<xs:complexType mixed="true">
   			<xs:attribute name="name" type="xs:string" use="required">
   				<xs:annotation>
   					<xs:documentation>Ссылка на field-&gt;name</xs:documentation>
   				</xs:annotation>
   			</xs:attribute>
   		</xs:complexType>
   	</xs:element>

	<xs:complexType name="Actions">
	    <xs:sequence>
	        <xs:element ref="action" minOccurs="1" maxOccurs="unbounded"/>
	    </xs:sequence>
	</xs:complexType>

	<xs:complexType name="OperationOptions">
		<xs:sequence>
			<xs:element ref="form"/>
			<xs:element ref="check" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="check">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="form">
		<xs:annotation>
			<xs:documentation>Форма</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/taatta/PurchaseSaleCurrencyPayment/PurchaseSaleCurrencyPayment.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="PurchaseSaleCurrencyPayment" description="Покупка/продажа иностранной валюты"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
	<implementation class="com.rssl.phizic.business.documents.InternalTransfer"/>
	<fields>
		<field
				name="documentNumber"
				description="Номер документа"
				type="string"
				source="document-number"
				signable="true">
		</field>
		<field name="state"
		       source="state"
		       description="Статус платежа"
			   type="string"/>
		<field
				name="documentDate"
				description="Дата документа"
				type="date"
				source="document-date"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
				<validator class="com.rssl.common.forms.validators.DatePeriodFieldValidator">
					<message text="Дата документа должна быть не раньше текущей и не позже 10 дней – срока действия документа."/>
					<parameter name="after">10</parameter>
				</validator>
			</validators>
		</field>

		<field name="admissionDate"
		       source="admissionDate"
			   type="date"
		       description="Дата приема плaтежа банком">
			<validators>
				<validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
			</validators>
		</field>

		<field
				name="payerAccountSelect"
				description="Счет списания"
				type="account"
				source="payer-account"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.phizic.business.payments.forms.validators.AccountIsOpenValidator"/>
			</validators>
		</field>

		<field
				name="receiverAccountSelect"
				description="Счет зачисления"
				type="account"
				source="receiver-account"
				signable="true">

			<validators>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
				<validator class="com.rssl.phizic.business.payments.forms.validators.AccountIsOpenValidator"/>
			</validators>
		</field>

		<field
				name="foreignCurrencyAmount"
				description="Сумма"
				source="foreign-amount"
				type="money"
				signable="true">

			<validators>
				<validator class="com.rssl.common.forms.validators.MoneyFieldValidator">
					<message
							text="Значение суммы в иностранной валюте должно быть в диапазоне 0,01 - 999999999,99"/>
				</validator>
				<validator class="com.rssl.common.forms.validators.NumericRangeValidator">
					<message text="Значение суммы в иностранной валюте должно быть в диапазоне 0,01 - 999999999,99"/>
					<parameter name="minValue">0.01</parameter>
					<parameter name="maxValue">999999999.99</parameter>
				</validator>
				<validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			</validators>
		</field>

		<field
				name="foreignCurrency"
				description="Иностранная валюта"
				source="extra-parameters/parameter[@name='foreign-currency']/@value"
				type="string"
				signable="true"/>

		<field
				name="rurCurrency"
				description="RUB"
				source="extra-parameters/parameter[@name='rur-currency']/@value"
				type="string"
				signable="true"/>

        <!--заполнил ли пользователь сумму списания (type=1) или сумму зачисления (type=2) в форме конверсии валюты
        эквивалентно: покупке валюты пользователем, если type=2, и продаже валюты пользователем, если type=1-->
		<field name="type"
		       source="extra-parameters/parameter[@name='type']/@value"
		       description="тип заполняемого поля"
			   type="string"/>

		<field
				name="rurAmount"
				description="Сумма в рублях"
				source="extra-parameters/parameter[@name='rur-amount']/@value"
				type="money"
				signable="true"/>

		<field
				name="course"
				description="Курс покупки/продажи"
				source="extra-parameters/parameter[@name='course']/@value"
				signable="true"/>

	</fields>

	<form-validators>
		<form-validator
				class="com.rssl.phizic.business.payments.forms.validators.ForeignAccountCurrencyPerfectValidator">
			<message text="Валюта счета не совпадает с выбранным видом валюты"/>
			<field-ref name="payerAccount">payerAccountSelect</field-ref>
			<field-ref name="receiverAccount">receiverAccountSelect</field-ref>
			<field-ref name="foreignCurrency">foreignCurrency</field-ref>
			<field-ref name="type">type</field-ref>
		</form-validator>
		<form-validator class="com.rssl.phizic.business.claims.forms.validators.EqualToOneFromParametersValidator">
			<message text="Указан неправильный тип открываемого счета"/>
			<field-ref name="parameterName">foreignCurrency</field-ref>
			<parameter name="param1">USD</parameter>
			<parameter name="param2">EUR</parameter>
		</form-validator>
	</form-validators>
</payment-form>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/globals/RollbackOrderClaim/RollbackOrderClaim.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="RollbackOrderClaim" description="Отмена оплаты товара из интернет-магазина"
              detailedDescription="Форма отмены оплаты"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
    <implementation class="com.rssl.phizic.business.documents.RollbackOrderClaim"/>

    <fields>
        <field
		        name="documentNumber"
		        description="Номер отзыва"
		        type="string"
		        source="document-number">
        </field>

		<field name="state"
		       source="state"
		       description="Статус платежа"
		       type="string"/>

		<field
				name="documentDate"
				description="Дата отзыва"
				type="date"
				source="document-date">
        </field>

	    <field
			    name="recalledDocumentNumber"
			    description="Номер отзываемого перевода"
			    type="string"
			    source="extra-parameters/parameter[@name='recalled-document-number']/@value">
        </field>

         <field
			    name="recalledDocumentFormName"
			    description="Форма отзываемого документа"
			    source="extra-parameters/parameter[@name='recalled-document-form-name']/@value"
			    type="string">
        </field>

	    <field
			    name="amountCurrency"
			    description="Валюта"
			    source="amount-currency"
			    type="string"/>

		<field
				name="amount"
				description="Сумма возврата"
				source="amount"
				type="money">
		</field>

	    <field
			    name="parentId"
			    description="Ссылка на отзываемый платеж"
			    source="extra-parameters/parameter[@name='parent-id']/@value"
			    type="string">
        </field>

        <field
			    name="externalDocumentId"
			    description="Идентификатор документа возврата в интернет-магазине"
			    source="extra-parameters/parameter[@name='external-document-id']/@value"
			    type="string">
        </field>

        <field
                name="refundUuid"
                description="Идентификатор возврата"
                source="extra-parameters/parameter[@name='refund-uuid']/@value"
                type="string">
        </field>
    </fields>
</payment-form>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/globals/GetPrivateOperationScanClaim/GetPrivateOperationScanClaim.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="GetPrivateOperationScanClaim"
              description="Заявка на получение копии  документа на  электронную почту"
              detailedDescription="Документ подтверждённый электронной подписью будет отправлен на указанный e-mail."
              confirmDescription="Заявка успешно отправлена в банк. После ее обработки Вы сможете принять на счет депо ценные бумаги данного вида. Спасибо, что Вы воспользовались «Сбербанк Онлайн»!"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
    <implementation class="com.rssl.phizic.business.documents.GetPrivateOperationScanClaim"/>

    <fields>
        <field  name="state"
                description="Статус заявки"
                type="string"
                source="state"/>

        <field  name="documentNumber"
                description="Номер заявки"
                type="string"
                source="document-number"/>

        <field  name="documentDate"
                description="Дата заявки"
                type="date"
                source="document-date"/>

        <field  name="client-fio"
                description="ФИО клиента"
                type="string"
                subType="static"
                source="extra-parameters/parameter[@name='client-fio']/@value">
        </field>

        <field  name="account-number"
                description="Номер счёта"
                type="string"
                subType="static"
                source="extra-parameters/parameter[@name='account-number']/@value">
        </field>

        <field  name="amount"
                description="Сумма"
                type="string"
                subType="static"
                source="extra-parameters/parameter[@name='amount']/@value">
        </field>

        <field  name="debit"
                description="расходная операция"
                type="string"
                subType="static"
                source="extra-parameters/parameter[@name='debit']/@value">
        </field>

        <field  name="authorisation-code"
                description="Код авторизации"
                type="string"
                subType="static"
                source="extra-parameters/parameter[@name='authorisation-code']/@value">
        </field>

        <field  name="e-mail"
                description="Электронный адрес"
                type="string"
                subType="static"
                source="extra-parameters/parameter[@name='e-mail']/@value">
        </field>

        <field  name="send-operation-date"
                description="Дата операции"
                type="date"
                subType="static"
                source="extra-parameters/parameter[@name='send-operation-date']/@value">
        </field>

    </fields>
</payment-form>
