=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/PaymentForm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="message">
		<xs:complexType>
			<xs:attribute name="text" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Текстовое сообщение об ошибке</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parameter">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="template" type="xs:boolean" default="true">
				<xs:annotation>
					<xs:documentation>
						Флаг, определяющий используется ли действие в шаблоне
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="order" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>
						Число, определяющее порядок исполнения
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="payment-form">
		<xs:annotation>
			<xs:documentation>Метаданные описывающие форму платежа</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="implementation">
					<xs:annotation>
						<xs:documentation>Класс имплементации платежа</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="template-implementation" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Класс имплементации шаблона платежа</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="statemachine" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Положение statemachine</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>

				<xs:element name="extended-metadata-loader" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Класс загрузчик доп полей</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="withdraw-options" minOccurs="0" type="OperationOptions">
					<xs:annotation>
						<xs:documentation>Настройки отзыва документа</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="edit-options" minOccurs="0" type="OperationOptions">
					<xs:annotation>
						<xs:documentation>Настройки редактирования документа</xs:documentation>
					</xs:annotation>
				</xs:element>

				<xs:element name="list-form" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="need-parent" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="value" type="xs:boolean" default="false"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="field" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="dictionaries" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Статические справочники формы</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entity-list" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:any namespace="##any" processContents="skip" minOccurs="0"
										        maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Элемент справочника вида  ключ-значение</xs:documentation>
											</xs:annotation>
										</xs:any>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Название справочника</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="form-validators" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Валидаторы формы</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="form-validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя формы</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" use="required">
				<xs:annotation>
					<xs:documentation>Название отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="templateName" use="optional">
				<xs:annotation>
					<xs:documentation>Название шаблона</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="detailedDescription" use="optional">
				<xs:annotation>
					<xs:documentation>Описание отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="confirmDescription" use="optional">
				<xs:annotation>
					<xs:documentation>Подтверждение отображаемое в UI</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="form-validator">
		<xs:annotation>
			<xs:documentation>Валидатор осуществляющий проверку полей формы (например, что первая дата в периоде дат не превышает вторую)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="field-ref" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="error-field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Класс реализующий данный валидатор</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="mode" type="xs:string" default="document|template">
				<xs:annotation>
					<xs:documentation>
                        режим работы валидатора. данное поле используется стратегиями валдиции.
                        см com.rssl.common.forms.processing.ValidationStrategy
                    </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="validator">
		<xs:annotation>
			<xs:documentation>Проверка отдельного поля формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="message" minOccurs="0"/>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя класса валидатора</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="mode" type="xs:string" default="document|template|mobile">
				<xs:annotation>
					<xs:documentation>
                        режим работы валидатора. данное поле используется стратегиями валдиции.
                        см com.rssl.common.forms.processing.ValidationStrategy
                    </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field">
		<xs:annotation>
			<xs:documentation>Поле формы</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="validators" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Набор валидаторов для данного поля</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="validator" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="formater" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Класс форматирующий вывод</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="parser" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="class" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Класс для разбора ввода</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя поля формы, используется в Payment -&gt; HTML преобразовании</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="source" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>XPath выражение для получения значения поля из Payment</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="description" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Описание поля, используется для вывода сообщеий валидации</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" type="xs:string" use="optional" default="string">
				<xs:annotation>
					<xs:documentation>Тип поля, по умочанию string</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="subType" use="optional" default="dinamic">
				<xs:annotation>
					<xs:documentation>Доп. тип поля, по умолчанию dinamic</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="dinamic"/>
                        <xs:enumeration value="static"/>
                    </xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute name="category" use="optional">
				<xs:annotation>
					<xs:documentation>Бизнес категория поля</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="phone"/>
                        <xs:enumeration value="surname"/>
                        <xs:enumeration value="extended_phone"/>
                        <xs:enumeration value="street"/>
                        <xs:enumeration value="date"/>
                        <xs:enumeration value="full_masked"/>
                        <xs:enumeration value="external_card"/>
                    </xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute name="mask" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Маска поля</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="signable" default="false" type="xs:boolean"/>
			<xs:attribute name="enabled" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>выражение булевого типа. Если результат true, то поле включено.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="fromApi" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Начиная с какой версии mobile API включается данное поле(только для mobile Api)(либо fromApi либо toApi)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
            <xs:attribute name="toApi" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>До какой версии mobile API включается данное поле(только для mobile Api)(либо fromApi либо toApi)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Вычислимое значение поля.</xs:documentation>
			</xs:annotation>
			</xs:attribute>
			<xs:attribute name="inital" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Начальное значение поля.</xs:documentation>
			</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="field-ref">
		<xs:annotation>
			<xs:documentation>Ссылки на поля требуемые для проверки</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Ссылка на field-&gt;name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>Свойство</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Устанавливает добавочный атрибут</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:annotation>
			<xs:documentation>Параметры валидации</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Имя параметра валидатора</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="error-field">
   		<xs:annotation>
   			<xs:documentation>Поле, которое нужно подсвечивать как ошибочное</xs:documentation>
   		</xs:annotation>
   		<xs:complexType mixed="true">
   			<xs:attribute name="name" type="xs:string" use="required">
   				<xs:annotation>
   					<xs:documentation>Ссылка на field-&gt;name</xs:documentation>
   				</xs:annotation>
   			</xs:attribute>
   		</xs:complexType>
   	</xs:element>

	<xs:complexType name="Actions">
	    <xs:sequence>
	        <xs:element ref="action" minOccurs="1" maxOccurs="unbounded"/>
	    </xs:sequence>
	</xs:complexType>

	<xs:complexType name="OperationOptions">
		<xs:sequence>
			<xs:element ref="form"/>
			<xs:element ref="check" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="check">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="form">
		<xs:annotation>
			<xs:documentation>Форма</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/globals/SaleCurrencyPayment/SaleCurrencyPayment.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="SaleCurrencyPayment" description="Продажа иностранной валюты" detailedDescription="Продажа иностранной валюты за рубли" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
  <implementation class="com.rssl.phizic.business.documents.InternalTransfer"/>
	<statemachine name="PaymentStateMachine"/>

	<withdraw-options>
	   <form name="RecallPayment"/>
	   <check class="com.rssl.phizic.business.documents.metadata.checkers.DocumentStateChecker">
		   <parameter name="state">dispatched</parameter>
	   </check>
	</withdraw-options>

	<fields>
    <field
      name="payerAccountSelect"
      description="Счет списания"
      type="account"
      source="payer-account"
      signable="true">

      <validators>
        <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
        <validator class="com.rssl.phizic.business.payments.forms.validators.UserAccountValidator"/>
      </validators>
    </field>

    <field
      name="receiverAccountSelect"
      description="Счет зачисления"
      type="account"
      source="receiver-account"
      signable="true">

      <validators>
        <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
        <validator class="com.rssl.phizic.business.payments.forms.validators.UserAccountValidator"/>
      </validators>
    </field>

    <field
      name="rurAmount"
      description="Сумма в рублях"
	  source="extra-parameters/parameter[@name='buy-amount']/@value"
	  type="money"
	  signable="true">

      <validators>
        <validator class="com.rssl.common.forms.validators.MoneyFieldValidator">
          <message text="Значение суммы в рублях должно быть в диапазоне 0,01 - 999999999,99"/>
          <parameter name="minValue">0.01</parameter>
          <parameter name="maxValue">999999999.99</parameter>
        </validator>
      </validators>
    </field>

    <field
      name="foreignCurrencyAmount"
      description="Сумма в иностранной валюте"
      source="amount"
	  type="money"
	  signable="true">

      <validators>
        <validator class="com.rssl.common.forms.validators.MoneyFieldValidator">
          <message text="Значение суммы в иностранной валюте должно быть в диапазоне 0,01 - 999999999,99"/>
          <parameter name="minValue">0.01</parameter>
		  <parameter name="maxValue">999999999.99</parameter>
        </validator>
      </validators>
    </field>

	<field
      name="foreignCurrency"
      description="Иностранная валюта"
      source="amount-currency"
	  type="string"
	  signable="true"/>

	<field
      name="rurCurrency"
      description="RUB"
      source="extra-parameters/parameter[@name='buy-amount-currency']/@value"
	  type="string"
	  signable="true"/>

	<field
      name="operationCode"
      description="Код валютной операции"
      source="extra-parameters/parameter[@name='operation-code']/@value"
	  type="string"
	  signable="true">
		<validators>
			<validator  mode="document"
						enabled="(form.payerAccountSelect.toString().substring(0, 5) == '40807' || form.payerAccountSelect.toString().substring(0, 5) == '40820' || form.payerAccountSelect.toString().substring(0, 3) == '426' || form.receiverAccountSelect.toString().substring(0, 5) == '40807' || form.receiverAccountSelect.toString().substring(0, 5) == '40820' || form.receiverAccountSelect.toString().substring(0, 3) == '426') &amp;&amp; (((form.receiverAccountSelect.toString().substring(0, 5) == '40817' || form.receiverAccountSelect.toString().substring(0, 5) == '40819' || form.receiverAccountSelect.toString().substring(0, 5) == '40820' || form.receiverAccountSelect.toString().substring(0, 5) == '40813' || form.receiverAccountSelect.toString().substring(0, 5) == '40814' || form.receiverAccountSelect.toString().substring(0, 5) == '40815' || form.receiverAccountSelect.toString().substring(0, 3) == '426' || (form.receiverAccountSelect.toString().substring(0, 5) == '40818' &amp;&amp; (form.receiverAccountSelect.toString().substring(13, 15) == '14' || form.receiverAccountSelect.toString().substring(13, 15) == '15' || form.receiverAccountSelect.toString().substring(13, 15) == '16' || form.receiverAccountSelect.toString().substring(13, 15) == '17' || form.receiverAccountSelect.toString().substring(13, 15) == '18'))) &amp;&amp;  form.payerAccountSelect.toString().substring(0, 5) != '40817' &amp;&amp; form.payerAccountSelect.toString().substring(0, 3) != '423')) || ((form.payerAccountSelect.toString().substring(0,5) == '40820' || form.payerAccountSelect.toString().substring(0,3) == '426'))"
			            class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
		</validators>
	  </field>

		<field name="state"
		       source="state"
		       description="Статус платежа"
			   type="string"/>

  </fields>

  <form-validators>
	<form-validator
	  mode="document"
	  class="com.rssl.phizic.business.payments.forms.validators.AccountAmountValidator">
	    <parameter name="amountMayBeNull">true</parameter>
	    <field-ref name="account">payerAccountSelect</field-ref>
	    <field-ref name="amount">foreignCurrencyAmount</field-ref>
	</form-validator>

    <form-validator 
	  mode="document"
	  class="com.rssl.phizic.business.payments.forms.validators.OnlyOneAmountFieldRequiredValidator">
		<message text="Не установлено значение суммы ни в одном из полей"/>
    	<field-ref name="field_1">rurAmount</field-ref>
    	<field-ref name="field_2">foreignCurrencyAmount</field-ref>
    </form-validator>

	<form-validator
	  mode="document"
	  class="com.rssl.phizic.business.payments.forms.validators.AccountsFromOneBranchValidator">
		<message text="Счет зачисления должен быть открыт в том же филиале, что и счет списания"/>
	    <field-ref name="fromAccount">payerAccountSelect</field-ref>
	    <field-ref name="toAccount">receiverAccountSelect</field-ref>
	</form-validator>
  </form-validators>
</payment-form>

=== e-r-i-b/e-r-i-b/e-r-i-b/Business/settings/payments/taatta/ConvertCurrencyPayment/ConvertCurrencyPayment.pfd.xml
<?xml version="1.0" encoding="windows-1251"?>
<payment-form name="ConvertCurrencyPayment" description="Конверсия иностранной валюты" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../PaymentForm.xsd">
  <implementation class="com.rssl.phizic.business.documents.InternalTransfer"/>
	<sender class="com.rssl.phizic.business.payments.forms.meta.DefaultBusinessDocumentSender"/>
  <fields>
	  <field
			  name="documentNumber"
			  description="Номер документа"
			  type="string"
			  source="document-number"
			  signable="true">
	  </field>
	  <field name="state"
	         source="state"
	         description="Статус платежа"
		     type="string"/>
	  <field
		     name="stateDescription"
	         source="stateDescription"
	         description="Описание статуса"
		     type="string"/>
	  <field
			  name="documentDate"
			  description="Дата документа"
			  type="date"
			  source="document-date"
			  signable="true">

		  <validators>
			  <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
			  <validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
			  <validator class="com.rssl.common.forms.validators.DatePeriodFieldValidator">
				  <message text="Дата документа должна быть не раньше текущей и не позже 10 дней – срока действия документа."/>
				  <parameter name="after">10</parameter>
			  </validator>
		  </validators>
	  </field>

	  <field name="admissionDate"
	         source="admissionDate"
		     type="date"
	         description="Дата приема плaтежа банком">
		  <validators>
			  <validator class="com.rssl.common.forms.validators.DateFieldValidator"/>
		  </validators>
	  </field>

	  <field
	        name="payerAccountSelect"
	        description="Счет списания"
	        type="string"
	        source="payer-account">

	        <validators>
	          <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
	          <validator class="com.rssl.phizic.business.payments.forms.validators.UserAccountValidator"/>
	        </validators>
	      </field>

	      <field
	        name="receiverAccountSelect"
	        description="Счет зачисления"
	        type="string"
	        source="receiver-account">

	        <validators>
	          <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
	          <validator class="com.rssl.phizic.business.payments.forms.validators.UserAccountValidator"/>
	        </validators>
	      </field>

	      <field
	        name="sellAmount"
	        description="Сумма"
	        source="sell-amount"
		    type="money">

	        <validators>
	          <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
	          <validator class="com.rssl.common.forms.validators.MoneyFieldValidator">
	            <message text="Значение суммы должно быть в диапазоне 0,01 - 999999999,99"/>
	          </validator>
	          <validator class="com.rssl.common.forms.validators.NumericRangeValidator">
	            <message text="Значение суммы должно быть в диапазоне 0,01 - 999999999,99"/>
	            <parameter name="minValue">0.01</parameter>
	            <parameter name="maxValue">999999999.99</parameter>
	          </validator>
	        </validators>
	      </field>

		  <field
	        name="sellAmountCurrency"
	        description="Валюта для продажи"
	        source="extra-parameters/parameter[@name='sell-amount-currency']/@value"
		    type="string"/>

         <field
	        name="buyAmount"
	        description="Сумма"
	        source="extra-parameters/parameter[@name='buy-amount']/@value"
		    type="money">

	        <validators>
	          <validator mode="document" class="com.rssl.common.forms.validators.RequiredFieldValidator"/>
	          <validator class="com.rssl.common.forms.validators.MoneyFieldValidator">
	            <message text="Значение суммы должно быть в диапазоне 0,01 - 999999999,99"/>
	          </validator>
	          <validator class="com.rssl.common.forms.validators.NumericRangeValidator">
	            <message text="Значение суммы должно быть в диапазоне 0,01 - 999999999,99"/>
	            <parameter name="minValue">0.01</parameter>
	            <parameter name="maxValue">999999999.99</parameter>
	          </validator>
	        </validators>
	      </field>

		  <field
	        name="buyAmountCurrency"
	        description="Валюта для покупки"
	        source="extra-parameters/parameter[@name='buy-amount-currency']/@value"
		    type="string"/>

	  <field
			  name="course"
			  description="Курс"
			  source="extra-parameters/parameter[@name='course']/@value"
			  signable="true"/>
  </fields>

  <form-validators>
 	<form-validator class="com.rssl.phizic.business.payments.forms.validators.AccountsNotEqualValidator">
		<field-ref name="fromAccount">payerAccountSelect</field-ref>
		<field-ref name="toAccount">receiverAccountSelect</field-ref>
	</form-validator>

	<form-validator class="com.rssl.phizic.business.payments.forms.validators.AccountCurrenciesNotEqualValidator">
		<message text="Валюта счета списания и валюта счета зачисления должны быть различны"/>
		<field-ref name="fromAccount">payerAccountSelect</field-ref>
		<field-ref name="toAccount">receiverAccountSelect</field-ref>
	</form-validator>

	<form-validator mode="document" class="com.rssl.phizic.business.payments.forms.validators.AccountAmountValidator">
	    <field-ref name="account">payerAccountSelect</field-ref>
	    <field-ref name="amount">sellAmount</field-ref>
	</form-validator>
  </form-validators>
</payment-form>
