=== e-r-i-b/e-r-i-b/e-r-i-b/Settings/schemas/operations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by qwe (ORiON) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="operations-config">
		<xsd:annotation>
			<xsd:documentation>Настройки ресурсов \ операций \ схем</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="resources">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="resource" type="Resource" minOccurs="0" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="operations">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="operation" type="Operation" minOccurs="0" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="services">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="service" type="Service" minOccurs="0" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="schemes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="scheme" type="Scheme" maxOccurs="unbounded"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="default-client-scheme" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="scheme-ref" type="SchemeRef"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="anonymous-client-scheme" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="scheme-ref" type="SchemeRef"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="default-admin-scheme" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="scheme-ref" type="SchemeRef"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="buildin-admin-scheme" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="scheme-ref" type="SchemeRef"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sms-banking-scheme" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="scheme-ref" type="SchemeRef"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Operation">
		<xsd:annotation>
			<xsd:documentation>Опперации</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="methods" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="remove" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" type="xsd:string"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="restriction" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="interface" use="required"/>
					<xsd:attribute name="default" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:ID" use="required"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="strategy" type="xsd:string" use="optional"/>
		<xsd:attribute name="tag" type="xsd:normalizedString" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="Service">
		<xsd:annotation>
			<xsd:documentation>"Услуги"</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="operation-ref" type="OperationRef" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="key" type="xsd:ID" use="required"/>
		<xsd:attribute name="category" type="operationKind" use="required"/>
        <xsd:attribute name="caadmin" type="xsd:boolean" use="optional" default="false"/>
	</xsd:complexType>
	<xsd:complexType name="Scheme">
		<xsd:annotation>
			<xsd:documentation>Схемы прав доступа</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="services">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="service-ref" type="ServiceRef" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:ID" use="required"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="category" type="operationKind" use="optional"/>
        <xsd:attribute name="caadmin" type="xsd:boolean" use="optional" default="false"/>
	</xsd:complexType>
	<xsd:complexType name="OperationRef">
		<xsd:annotation>
			<xsd:documentation>Ссылка на операцию</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="key" type="xsd:IDREF" use="required"/>
		<xsd:attribute name="spread" type="xsd:boolean" use="optional" default="true">
			<xsd:annotation>
				<xsd:documentation>Если задан то операция не может быть использована в другом сервисе.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="ServiceRef">
		<xsd:annotation>
			<xsd:documentation>Ссылка на услугу</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="key" type="xsd:IDREF" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="SchemeRef">
		<xsd:annotation>
			<xsd:documentation>Ссылка на схему прав</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="key" type="xsd:IDREF" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="Resource">
		<xsd:annotation>
			<xsd:documentation>Ресурс</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="key" type="xsd:string" use="required"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="class" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="operationKind">
		<xsd:annotation>
			<xsd:documentation>тип операции</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="admin"/>
			<xsd:enumeration value="client"/>
			<xsd:enumeration value="system"/>
			<xsd:enumeration value="general"/>
			<xsd:enumeration value="employee"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/Settings/configs/sbercred/operations.xml
<?xml version="1.0" encoding="windows-1251"?>

<operations-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/operations.xsd">

	<resources>
		<resource key="ActivePerson" name="Пользователь"
		          class="com.rssl.phizic.business.persons.ActivePerson"/>
		<resource key="AccessScheme" name="Схема доступа"
		          class="com.rssl.phizic.business.schemes.SharedAccessScheme"/>
		<resource key="AccountLink" name="Счет"
		          class="com.rssl.phizic.business.resources.external.AccountLink"/>
		<resource key="CardLink" name="Карта" class="com.rssl.phizic.business.resources.external.CardLink"/>
	</resources>

	<operations>

		<!-- !!! Для пользователя !!! -->

				<!-- Общие -->
		<!-- Сокрытие курса валют -->
		<operation key="ShowCurrenciesRateOperation"
		           name="Доступ к курсам валют"
		           class="com.rssl.phizic.operations.currency.ShowCurrenciesRateOperation"
		           tag="client">
		</operation>

		<!-- Просмотр журнала последних операций -->
		<operation key="GetLastUserLogEntriesOperation"
		           name="Получение информации о последних операциях клиента"
		           class="com.rssl.phizic.operations.log.GetLastUserLogEntriesOperation"
		           tag="client">
		</operation>

		<!-- Печать мемориального ордера -->
		<operation key="PrintMemOperation"
		           name="Печать платежного поручения"
		           class="com.rssl.phizic.operations.payment.PrintMemOperation"
		           tag="client">
		</operation>

		<!-- Операции со счетами -->
		<operation key="GetAccountsOperation"
		           name="Доступ к списку счетов"
		           class="com.rssl.phizic.operations.account.GetAccountsOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.resources.external.AccountFilter"
			             default="com.rssl.phizic.business.resources.external.NullAccountFilter"/>
		</operation>

		<operation key="GetAccountAbstractOperation"
		           name="Получение выписки по счету"
		           class="com.rssl.phizic.operations.account.GetAccountAbstractOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.resources.external.AccountFilter"
			             default="com.rssl.phizic.business.resources.external.NullAccountFilter"/>
		</operation>

		<operation key="ShowLongOfferOperation"
		           name="Отчет об исполнении длительных поручений"
		           class="com.rssl.phizic.operations.account.ShowLongOfferOperation"
		           tag="client">
		</operation>

		<operation key="GetAccountInfoOperation"
		           name="Получение информации по счёту"
		           class="com.rssl.phizic.operations.account.GetAccountInfoOperation"
		           tag="client">
		</operation>

		<operation key="AccountInfoPrintOperation"
		           name="Печать информации о счете"
		           class="com.rssl.phizic.operations.print.AccountInfoPrintOperation"
		           tag="client"/>

		<!-- Операции с картами -->
		<operation key="GetCardsOperation"
		           name="Доступ к списку карт"
		           class="com.rssl.phizic.operations.card.GetCardsOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.operations.restrictions.CardRestriction"
			             default="com.rssl.phizic.business.operations.restrictions.defaults.NullCardRestriction"/>
		</operation>

		<operation key="GetCardAbstractOperation"
		           name="Получение выписки по карте"
		           class="com.rssl.phizic.operations.card.GetCardAbstractOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.operations.restrictions.CardRestriction"
			             default="com.rssl.phizic.business.operations.restrictions.defaults.NullCardRestriction"/>
		</operation>

		<operation key="GetCardInfoOperation"
		           name="Получение информации по картам"
		           class="com.rssl.phizic.operations.card.GetCardInfoOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.operations.restrictions.CardRestriction"
			             default="com.rssl.phizic.business.operations.restrictions.defaults.NullCardRestriction"/>
		</operation>

		<operation key="CardInfoPrintOperation"
		           name="Печать информации о счете"
		           class="com.rssl.phizic.operations.card.GetCardInfoOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.operations.restrictions.CardRestriction"
			             default="com.rssl.phizic.business.operations.restrictions.defaults.NullCardRestriction"/>
		</operation>

		<!-- Операции с формами платежей -->
		<operation key="CreateFormPaymentOperation"
		           name="Создание платежа"
		           class="com.rssl.phizic.operations.payment.CreateFormPaymentOperation"
		           tag="client"/>

		<operation key="CreateFormPaymentGuidOperation"
		           name="Создание платежа (guid for anonymous)"
		           class="com.rssl.phizic.operations.payment.CreateFormPaymentGuidOperation"
		           tag="client"/>

		<operation key="ConfirmFormPaymentOperation"
		           name="Подтверждение платежа"
		           class="com.rssl.phizic.operations.payment.ConfirmFormPaymentOperation"
		           tag="client"/>

		<operation key="ViewDocumentOperation"
		           name="Просмотр/печать документа"
		           class="com.rssl.phizic.operations.forms.ViewDocumentOperation"
		           tag="client"/>

		<operation key="GetMetaPaymentListOperation"
		           name="Список платежей на основе формы"
		           class="com.rssl.phizic.operations.payment.GetMetaPaymentListOperation"
		           tag="client"/>

		<!-- Операции c депозитами -->
		<operation key="GetDepositProductsListOperation"
		           name="Список депозитных продуктов"
		           class="com.rssl.phizic.operations.deposits.GetDepositProductsListOperation"
		           tag="client">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.DepositProductRestriction"
					default="com.rssl.phizic.business.operations.restrictions.defaults.PersonDepartmentDepositProductRestriction"/>
		</operation>

		<operation key="GetDepositListOperation"
		           name="Список депозитов (вкладов) клиента"
		           class="com.rssl.phizic.operations.deposits.GetDepositListOperation"
		           tag="client"/>

		<operation key="DepositDetailsOperation"
		           name="Полная информация о депозитном продукте"
		           class="com.rssl.phizic.operations.deposits.DepositDetailsOperation"
		           tag="general">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.DepositProductRestriction"
					default="com.rssl.phizic.business.operations.restrictions.defaults.PersonDepartmentDepositProductRestriction"/>
		</operation>

		<operation key="DepositCalculatorOperation"
		           name="Калькулятор депозитных продуктов"
		           class="com.rssl.phizic.operations.deposits.DepositCalculatorOperation"
		           tag="client">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.DepositProductRestriction"
					default="com.rssl.phizic.business.operations.restrictions.defaults.PersonDepartmentDepositProductRestriction"/>
		</operation>

		<operation key="GetDepositInfoOperation"
		           name="Получение информации по вкладу"
		           class="com.rssl.phizic.operations.deposits.GetDepositInfoOperation"
		           tag="client">
		</operation>

		<operation key="GetDepositAbstractOperation"
		           name="Получение выписки по вкладу"
		           class="com.rssl.phizic.operations.deposits.GetDepositAbstractOperation"
		           tag="client">
			<restriction interface="com.rssl.phizic.business.operations.restrictions.DepositProductRestriction"
			             default="com.rssl.phizic.business.operations.restrictions.defaults.PersonDepartmentDepositProductRestriction"/>
		</operation>

		<operation key="DepositInfoPrintOperation"
		           name="Печать информации о депозите"
		           class="com.rssl.phizic.operations.print.DepositInfoPrintOperation"
		           tag="client"/>

		<!--Операции с кредитами -->
		<operation key="GetLoanProductListOperation"
				   name="Список кредитных продуктов банка"
				   class="com.rssl.phizic.operations.loans.products.GetLoanProductListOperation"
				   tag="client">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.LoanProductRestriction"
					default="com.rssl.phizic.business.operations.restrictions.defaults.NullLoanProductRestriction"/>
		</operation>

		<operation key="LoanProductDetailsOperation"
		           name="Полная информация о кредитном продукте"
		           class="com.rssl.phizic.operations.loans.products.LoanProductDetailsOperation"
		           tag="client">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.LoanProductRestriction"
					default="com.rssl.phizic.business.operations.restrictions.defaults.NullLoanProductRestriction"/>
		</operation>

		<operation key="LoanCalculatorOperation"
		           name="Калькулятор кредитных продуктов"
		           class="com.rssl.phizic.operations.loans.LoanCalculatorOperation"
		           tag="client">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.LoanProductRestriction"
					default="com.rssl.phizic.business.operations.restrictions.defaults.NullLoanProductRestriction"/>
		</operation>

		<operation key="GetLoanListOperation"
				   name="Список кредитов клиента"
				   class="com.rssl.phizic.operations.loans.loan.GetLoanListOperation"
				   tag="client"/>

		<operation key="GetLoanInfoOperation"
		           name="Получение информации по кредиту"
		           class="com.rssl.phizic.operations.loans.loan.GetLoanInfoOperation"
		           tag="client">
			<restriction
					interface="com.rssl.phizic.business.operations.restrictions.LoanRestriction"
