=== e-r-i-b/e-r-i-b/e-r-i-b/Settings/schemas/receivers.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="1.0">

	<xsd:annotation>
		<xsd:appinfo>
			<jxb:schemaBindings>
				<jxb:package name="com.rssl.phizic.business.dictionaries.receivers.personal.generated"/>
				<jxb:nameXmlTransform>
					<jxb:elementName suffix="Element"/>
					<jxb:typeName suffix="Descriptor"/>
				</jxb:nameXmlTransform>
			</jxb:schemaBindings>
		</xsd:appinfo>
	</xsd:annotation>
	
	<xsd:element name="receivers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="receiver" type="Receiver" maxOccurs="unbounded" minOccurs="0">
                    <xsd:annotation>
                        <xsd:appinfo>
							<jxb:property name="receiverDescriptors"/>
						</xsd:appinfo>
                    </xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="Receiver">
        <xsd:annotation>
            <xsd:documentation>Получатель. У получателя всегда есть поле personId. Оно заполняется в EditPaymentReceiverAction, свойства в PersonalReceiversFieldsBuilder</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="field" type="Field" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:appinfo>
						<jxb:property name="fieldDescriptors"/>
					</xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
	        <xsd:element name="form-validators" minOccurs="0">
			   <xsd:annotation>
			        <xsd:documentation>Валидаторы формы для получателя</xsd:documentation>
			   </xsd:annotation>
			   <xsd:complexType>
			        <xsd:sequence>
				        <xsd:element name="form-validator" maxOccurs="unbounded" type="Form-validator"/>
			       </xsd:sequence>
			   </xsd:complexType>
		    </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="className" use="required" type="JavaClass"/>
	    <xsd:attribute name="kind"      use="required" type="xsd:string"/>
	    <xsd:attribute name="listkind"  use="required" type="xsd:string"/>
    </xsd:complexType>
	<xsd:complexType name="Field">
        <xsd:annotation>
            <xsd:documentation>Описание поля формы</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
	        <xsd:element name="format" minOccurs="0" type="Format"/>
            <xsd:element name="validators" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="validator" type="Validator" minOccurs="0" maxOccurs="unbounded">
                            <xsd:annotation>
                                <xsd:appinfo>
                                    <jxb:property name="validatorDescriptor"/>
                                </xsd:appinfo>
                            </xsd:annotation>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" use="required"/>
        <xsd:attribute name="description"   use="required"/>
		<xsd:attribute name="type"  use="optional"/>
		<xsd:attribute name="path" use="optional"/>
        <xsd:attribute name="required"  type="xsd:boolean" use="optional"/>
        <xsd:attribute name="minlength" type="xsd:integer" use="optional"/>
		<xsd:attribute name="maxlength" type="xsd:integer" use="optional"/>
    </xsd:complexType>
	<xsd:complexType name="Format">
        <xsd:annotation>
            <xsd:documentation>Проверка поля на соответствие шаблону</xsd:documentation>
        </xsd:annotation>
		<xsd:attribute name="regexp" use="required"/>
        <xsd:attribute name="message" use="required"/>
	</xsd:complexType>
    <xsd:complexType name="Validator">
        <xsd:annotation>
            <xsd:documentation>Описание валидатора отдельного поля формы</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="class" type="JavaClass">
                <xsd:annotation>
                    <xsd:appinfo>
						<jxb:property name="className"/>
					</xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs="0" name="message" type="Message"/>
            <xsd:element minOccurs="0" maxOccurs="unbounded" name="parameter" type="Parameter">
                <xsd:annotation>
                    <xsd:appinfo>
						<jxb:property name="parameterDescriptors"/>
					</xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
		<xsd:attribute name="template" type="xsd:boolean" use="optional" default="true"/>
    </xsd:complexType>
	<xsd:complexType name="Form-validator">
        <xsd:annotation>
            <xsd:documentation>Описание валидатора формы</xsd:documentation>
        </xsd:annotation>
		<xsd:sequence>
			<xsd:element name="class" type="JavaClass">
                <xsd:annotation>
                    <xsd:appinfo>
						<jxb:property name="className"/>
					</xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
			<xsd:element minOccurs="0" name="field-ref" maxOccurs="unbounded">
				<xsd:complexType mixed="true">
					<xsd:attribute name="name" type="xsd:string" use="required">
						<xsd:annotation>
							<xsd:documentation>Ссылка на field-&gt;name</xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element minOccurs="0" name="message" type="Message"/>
			<xsd:element minOccurs="0" name="parameter" maxOccurs="unbounded" type="Parameter">
				<xsd:annotation>
                   <xsd:appinfo>
						<jxb:property name="parameterDescriptors"/>
					</xsd:appinfo>
               </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="template" type="xsd:boolean" default="true">
			<xsd:annotation>
				<xsd:documentation>Используется ли данный валидатор при проверке шаблонов</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="enabled" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Javascript выражение булевого типа. Если результат true, то валидатор включен.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="Parameter">
        <xsd:annotation>
            <xsd:documentation>Параметр валидатора</xsd:documentation>
        </xsd:annotation>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" use="required" type="xsd:string"/>
    </xsd:complexType>
    <xsd:simpleType name="JavaClass">
        <xsd:annotation>
            <xsd:documentation>FQN java класса</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="Message">
        <xsd:annotation>
            <xsd:documentation>Сообщение</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string"/>
    </xsd:simpleType>
</xsd:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/Settings/configs/derjava/receivers.xml
<?xml version="1.0" encoding="windows-1251"?>
<receivers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="../../schemas/receivers.xsd">

	<receiver className="com.rssl.phizic.business.dictionaries.PaymentReceiverPhiz" kind="P" listkind="PJ">
		<field name="name"                  description="Наименование (ФИО)" required="true" maxlength="265"/>
		<field name="INN"                   description="ИНН"                required="true" maxlength="12" minlength="10"/>
		<field name="account"               description="Счет"               required="true">
			<format regexp="\d{20}" message="Номер счета должен содержать 20 цифр"/>
			<validators>
				<validator>
					<class>com.rssl.phizic.business.payments.forms.validators.AccountCurrencyValidator</class>
					<message>Валюта счета получателя отсутствует в справочнике валют. Обновите справочник и повторите попытку.</message>
				</validator>
			</validators>
		</field>
		<field name="bankName"              description="Наименование"       required="true"/>
		<field name="bankCode"              description="БИК"                required="true"/>
		<field name="correspondentAccount"  description="Корр. счет"         required="false">
			<format regexp="\d{20}" message="Номер корр. счета должен содержать 20 цифр"/>
		</field>
		<field name="description"           description="Дополнительные сведения"/>
	</receiver>

	<receiver className="com.rssl.phizic.business.dictionaries.PaymentReceiverJur" kind="J" listkind="PJ">
		<field name="name"                  description="Наименование (ФИО)"  required="true" maxlength="265"/>
		<field name="INN"                   description="ИНН"                 required="true" maxlength="10" minlength="10"/>
		<field name="KPP"                   description="КПП"                 required="true">
			<format regexp="\d{9}" message="КПП должен содержать 9 цифр"/>
		</field>
		<field name="account"               description="Счет"                required="true">
			<format regexp="\d{20}" message="Номер счета должен содержать 20 цифр"/>
			<validators>
				<validator>
					<class>com.rssl.phizic.business.payments.forms.validators.AccountCurrencyValidator</class>
					<message>Валюта счета получателя отсутствует в справочнике валют. Обновите справочник и повторите попытку.</message>
				</validator>
			</validators>
		</field>
		<field name="bankName"              description="Наименование"        required="true"/>
		<field name="bankCode"              description="БИК"                 required="true"/>
		<field name="correspondentAccount"  description="Корр. счет"          required="false">
			<format regexp="\d{20}" message="Номер корр. счета должен содержать 20 цифр"/>
		</field>
		<field name="description"           description="Дополнительные сведения"/>
	</receiver>
</receivers>

=== e-r-i-b/e-r-i-b/e-r-i-b/Settings/configs/sevb/receivers.xml
<?xml version="1.0" encoding="windows-1251"?>
<receivers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../../schemas/receivers.xsd">

	<receiver className="com.rssl.phizic.business.dictionaries.PaymentReceiverPhiz" kind="P" listkind="P">
		<field name="alias" description="Обозначение" required="true"/>
		<field name="name" description="Наименование (ФИО)" required="true" maxlength="265"/>
		<field name="INN" description="ИНН" maxlength="12" minlength="12">
			<format regexp="\d{12}" message="ИНН должен содержать 12 цифр"/>
		</field>
		<field name="account" description="Счет" required="true" maxlength="25">
			<format regexp="\d{20,25}" message="Номер счета должен содержать от 20 до 25 цифр"/>
			<validators>
				<validator>
					<class>com.rssl.phizic.business.payments.forms.validators.AccountCurrencyValidator</class>
					<message>Валюта счета получателя отсутствует в справочнике валют. Обновите справочник и повторите попытку.</message>
				</validator>
			</validators>
		</field>
		<field name="bankName" description="Наименование" required="true"/>
		<field name="bankCode" description="БИК" minlength="9" maxlength="9" required="true">
			<format regexp="\d{9}" message="БИК должен содержать 9 цифр"/>
            <validators>
                <validator>
                    <class>com.rssl.phizic.business.payments.forms.validators.BICFieldValidator</class>
                    <message>БИК банка получателя не найден в справочнике банков</message>
                </validator>
            </validators>
		</field>
		<field name="correspondentAccount" description="Корр. счет" required="true">
			<format regexp="\d{20,25}" message="Номер корр. счета должен содержать от 20 до 25 цифр"/>
		</field>
<!--
		<field name="description" description="Дополнительные сведения"/>
-->
		<form-validators>
			<form-validator>
				<class>com.rssl.phizic.business.payments.forms.validators.AccountKeyValidator</class>
					<field-ref name="receiverAccount">account</field-ref>
					<field-ref name="receiverBIC">bankCode</field-ref>
					<message>Неверный ключ счета.</message>
			</form-validator>
		</form-validators>
	</receiver>

	<receiver className="com.rssl.phizic.business.dictionaries.PaymentReceiverJur" kind="J" listkind="J">
		<field name="alias" description="Обозначение" required="true"/>
		<field name="name" description="Наименование (ФИО)" required="true" maxlength="265"/>
		<field name="INN" description="ИНН" required="true" maxlength="10" minlength="10">
			<format regexp="\d{10}" message="ИНН должен содержать 10 цифр"/>
		</field>
		<field name="account" description="Счет" required="true" maxlength="25">
			<format regexp="\d{20,25}" message="Номер счета должен содержать от 20 до 25 цифр"/>
			<validators>
				<validator>
					<class>com.rssl.phizic.business.payments.forms.validators.AccountCurrencyValidator</class>
					<message>Валюта счета получателя отсутствует в справочнике валют. Обновите справочник и повторите попытку.</message>
				</validator>
			</validators>
		</field>
		<field name="bankName" description="Наименование" required="true"/>
		<field name="bankCode" description="БИК" minlength="9" maxlength="9" required="true">
			<format regexp="\d{9}" message="БИК должен содержать 9 цифр"/>
            <validators>
                <validator>
                    <class>com.rssl.phizic.business.payments.forms.validators.BICFieldValidator</class>
                    <message>БИК банка получателя не найден в справочнике банков</message>
                </validator>
            </validators>
		</field>
		<field name="correspondentAccount" description="Корр. счет" required="true">
			<format regexp="\d{20,25}" message="Номер корр. счета должен содержать от 20 до 25 цифр"/>
		</field>
<!--
		<field name="description" description="Дополнительные сведения"/>
-->
		<form-validators>
			<form-validator>
				<class>com.rssl.phizic.business.payments.forms.validators.AccountKeyValidator</class>
				<field-ref name="receiverBIC">bankCode</field-ref>
				<field-ref name="receiverAccount">account</field-ref>
				<message>Неверный ключ счета получателя</message>
			</form-validator>
		</form-validators>

	</receiver>
</receivers>
