=== e-r-i-b/e-r-i-b/e-r-i-b/Gate/src/com/rssl/phizic/gate/messaging/configuration/messaging.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            jxb:version="1.0">
	<xsd:element name="messaging-config">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="request" type="Request" maxOccurs="unbounded" minOccurs="0">
					<xsd:annotation>
						<xsd:appinfo>
							<jxb:property name="requests"/>
						</xsd:appinfo>
					</xsd:annotation>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Request">
		<xsd:sequence>
			<xsd:element name="response" type="Response" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:appinfo>
						<jxb:property name="responses"/>
					</xsd:appinfo>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="attribute" maxOccurs="unbounded" minOccurs="0" type="Attribute">
				<xsd:annotation>
					<xsd:appinfo>
						<jxb:property name="attributes"/>
					</xsd:appinfo>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" use="required" type="xsd:string"/>
		<xsd:attribute name="endpoint" type="xsd:string"/>
		<xsd:attribute name="subsystem" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Подсистема, для задания доп. инфо по обработке запроса</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
        <xsd:attribute name="cacheKeyClass" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>Полное имя класса для вычисления ключа кеша</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="Response">
		<xsd:attribute name="name" use="required" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="Attribute">
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="value" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== e-r-i-b/e-r-i-b/e-r-i-b/IQWaveGate/src/com/rssl/phizicgate/iqwave/messaging/iqwave-messaging-config.cfg.xml
<?xml version="1.0" encoding="utf-8"?>
<messaging-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="./../../../../../../../Gate/src/com/rssl/phizic/gate/messaging/configuration/messaging.xsd">
    <request endpoint="iqwave" name="CardToCardRequest">
        <response name="CardToCardResponse"/>
    </request>
    <request endpoint="iqwave" name="SimplePaymentRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="PaymentFnsRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="PaymentMgtsRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="PaymentGkhRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="PaymentMosenergoRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="PaymentDebtsFnsRequest">
        <response name="PaymentDebtsFnsResponse"/>
    </request>

    <request endpoint="iqwave" name="PaymentDebtsMgtsRequest">
        <response name="PaymentDebtsMgtsResponse"/>
    </request>

    <request endpoint="iqwave" name="PaymentDebtsGkhRequest">
        <response name="PaymentDebtsGkhResponse"/>
    </request>

    <request endpoint="iqwave" name="PaymentRostelecomRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="PaymentDebtsRostelecomRequest">
        <response name="PaymentDebtsRostelecomResponse"/>
    </request>

    <request endpoint="iqwave" name="AutoPayListRequest">
        <response name="AutoPayListResponse"/>
    </request>

    <request endpoint="iqwave" name="AutoPayReportRequest">
        <response name="AutoPayReportResponse"/>
    </request>

    <request endpoint="iqwave" name="AutoPayStateRequest" >
        <response name="AutoPayStateResponse"/>
    </request>

    <request endpoint="iqwave" name="FreePaymentRequest">
        <response name="OfflineTicket"/>
    </request>

    <request endpoint="iqwave" name="FNSFreePaymentRequest">
        <response name="OfflineTicket"/>
    </request>

    <!-- запрос на регистрацию автоплатежа-->
     <request endpoint="iqwave" name="AutoPayRegisterRequest">
        <response name="OfflineTicket"/>
    </request>

    <!-- запрос на редактирование автоплатежа-->
     <request endpoint="iqwave" name="AutoPayCorrectionRequest">
        <response name="OfflineTicket"/>
    </request>

    <!-- запрос на отмену автоплатежа-->
    <request endpoint="iqwave" name="AutoPayCancelRequest">
        <response name="OfflineTicket"/>
    </request>

    <!-- запрос на получение доступных типов автоплатежей -->
    <request endpoint="iqwave" name="AutoPayGetClientTypeRequest">
        <response name="AutoPayGetClientTypeResponse"/>
    </request>
    
    <request name="OperStatusRequest" endpoint="iqwave">
        <response name="OperStatusResponse"/>
    </request>

    <!-- запрос информации о броне (аэрофлот)-->
    <request name="PaymentCheckRESRequest" endpoint="iqwave">
        <response name="PaymentCheckRESResponse"/>
    </request>

    <!-- запрос на исполнение платежа об оплате брони (аэрофлот)-->
    <request name="PaymentRESRequest" endpoint="iqwave">
        <response name="OfflineTicket"/>
    </request>

    <!-- запрос коммисии для перевода на карту в другой банк -->
    <request name="CardToCardInfoRequest" endpoint="iqwave">
        <response name="CardToCardInfoResponse"/>
    </request>

    <!--Программа лояльности. Запрос информации по накопленным баллам-->
    <request name="LoyaltyGetBalanceRequest" endpoint="iqwave">
        <response name="LoyaltyGetBalanceResponse"/>
    </request>

    <!--Программа лояльности. Запрос информации по последним операциям-->
    <request name="LoyaltyGetStatementReportRequest" endpoint="iqwave">
        <response name="LoyaltyGetStatementReportResponse"/>
    </request>

    <!--Программа лояльности. Запрос информации по спецпредложениям-->
    <request name="LoyaltyGetOffersRequest" endpoint="iqwave">
        <response name="LoyaltyGetOffersResponse"/>
    </request>

    <!--Программа лояльности. заявка на регистрацию в программе лояльности-->
    <request name="LoyaltyRegisterRequest" endpoint="iqwave">
        <response name="LoyaltyRegisterResponse"/>
    </request>

    <!-- Запрос расписания рейсов Аэроэкспресс -->
    <request name="AeroexpressScheduleRequest" endpoint="iqwave">
        <response name="AeroexpressScheduleResponse"/>
    </request>

    <!-- Запрос прайс-листа Аэроэкспресс -->
    <request name="AeroexpressPricelistRequest" endpoint="iqwave">
        <response name="AeroexpressPricelistResponse"/>
    </request>

    <!-- Запрос на получение рейсов -->
    <request name="AeroexpressFreeSeatsGlobalRequest" endpoint="iqwave">
        <response name="AeroexpressFreeSeatsGlobalResponse"/>
    </request>

    <!-- Запрос на получение статусов мест по выбранному рейсу -->
    <request name="AeroexpressFreeSeatsDetailRequest" endpoint="iqwave">
        <response name="AeroexpressFreeSeatsDetailResponse"/>
    </request>

    <!-- Запрос на регистрацию получения билетов -->
    <request name="AeroexpressGetTicketRequest" endpoint="iqwave">
        <response name="AeroexpressGetTicketResponse"/>
    </request>
    
    <!-- Запрос на оплату билетов -->
    <request name="AeroexpressPayTicketRequest" endpoint="iqwave">
        <response name="AeroexpressPayTicketResponse"/>
    </request>

    <!--Отмена операции-->
    <request name="ReversalSimplePaymentEcommerceRequest" endpoint="iqwave">
        <response name="OfflineTicket"/>
    </request>

    <!--Возврат товара (билетов)-->
    <request name="RefundSimplePaymentEcommerceRequest" endpoint="iqwave">
        <response name="OfflineTicket"/>
    </request>

    <!--оплата интернет заказа-->
    <request endpoint="iqwave" name="SimplePaymentEcommerceRequest">
        <response name="OfflineTicket"/>
    </request>
</messaging-config>

=== e-r-i-b/e-r-i-b/e-r-i-b/RSRetailV6r20Gate/src/com/rssl/phizicgate/rsretailV6r20/messaging/retail-messaging.cfg.xml
<?xml version="1.0" encoding="utf-8"?>
<messaging-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="./../../../../../../../Gate/src/com/rssl/phizic/gate/messaging/configuration/messaging.xsd">

	<request endpoint="retail" name="internalTransfer_q" subsystem="business">
		<response name="internalTransfer_a"/>
	</request>

	<request endpoint="retail" name="openDeposit_q" subsystem="business">
		<response name="openDeposit_a"/>
	</request>

	<request endpoint="retail" name="closeDeposit_q" subsystem="business">
		<response name="closeDeposit_a"/>
	</request>

	<request endpoint="retail" name="externalTransfer_q" subsystem="business">
		<response name="externalTransfer_a"/>
	</request>

	<request endpoint="retail" name="carryDeposit_q" subsystem="scheduler">
		<response name="carryDeposit_a"/>
		<attribute name="needParseError" value="false"/>
	</request>

	<request endpoint="retail" name="getDepositList_q" subsystem="business">
		<response name="getDepositList_a"/>
	</request>

	<request endpoint="retail" name="depositProduct_q" subsystem="business">
		<response name="depositProduct_a"/>
	</request>

	<request endpoint="retail" name="getClientDepositInfo_q" subsystem="business" cacheKeyClass="com.rssl.phizicgate.rsretailV6r20.cache.ClientDepositInfoQ">
		<response name="getClientDepositInfo_a"/>
	</request>

	<request endpoint="retail" name="commissionPay_q" subsystem="business">
		<response name="commissionPay_a"/>
	</request>

	<request endpoint="retail" name="recallDocument_q" subsystem="business">
		<response name="recallDocument_a"/>
	</request>

	<request endpoint="retail" name="getAccountTransactions_q" subsystem="business">
		<response name="getAccountTransactions_a"/>
	</request>

	<request endpoint="retail" name="getCurrencyRate_q" subsystem="business" cacheKeyClass="com.rssl.phizicgate.rsretailV6r20.cache.GetCurrencyRateQ">
		<response name="getCurrencyRate_a"/>
	</request>

    <request endpoint="retail" name="getRateCB_q" subsystem="business">
        <response name="getRateCB_a"/>
    </request>

	<request endpoint="retail" name="serviceFeePayment_q" subsystem="business">
		<response name="serviceFeePayment_a"/>
	</request>

	<request endpoint="retail" name="getReferencFromDocument_q" subsystem="scheduler">
		<response name="getReferencFromDocument_a"/>
	</request>

	<request name="nextWorkDate_q" endpoint="retail" subsystem="business">
		<response name="nextWorkDate_a"/>
	</request>
	<request name="validatePayment_q" endpoint="retail" subsystem="business">
		<response name="validatePayment_a"/>
	</request>
	<request endpoint="retail" name="savingsBookLoss_q" subsystem="business">
		<response name="savingsBookLoss_a"/>
	</request>
</messaging-config>
